services:


  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data   # carpeta local vinculada a MinIO
      
  postgres:
    image: postgres:15
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.7.1
    container_name: airflow
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: ${AIRFLOW_PORT}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/start-airflow.sh:/opt/airflow/start-airflow.sh
    ports:
      - "${AIRFLOW_PORT}:${AIRFLOW_PORT}"
    command: ["bash", "/opt/airflow/start-airflow.sh"]


  spark-master:
    image: bitnami/spark:3.5
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077"   # puerto del master
      - "8080:8080"   # UI web del master

  spark-worker:
    image: bitnami/spark:3.5
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"   # UI web del worker

  dbt:
    image: ghcr.io/dbt-labs/dbt-core:1.5.2
    container_name: dbt
    env_file:
      - .env
    volumes:
      - ./dbt_project:/usr/app
      - ./warehouse:/data/warehouse  # carpeta local para DuckDB
      - ./minio_data:/data/minio
    working_dir: /usr/app
    command: sleep infinity

  streamlit:
    build:
      context: ./streamlit   # carpeta donde está el Dockerfile y app.py
    container_name: streamlit
    ports:
      - "${STREAMLIT_PORT}:8501"
    volumes:
      - ./warehouse:/data/warehouse   # acceso al duckdb
    env_file:
      - .env
    depends_on:
      - dbt
      - minio

volumes:
  postgres_data: